import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Food</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <header>
                    <nav className="navbar navbar-expand-sm text-dark">
                        <ul className="navbar-nav">
                            <li className="nav-item active">
                                <a className="nav-link" href="#">
                                    <Image
                                        src='/images/logo.png'
                                        alt='logo'
                                        width={50}
                                        height={43}
                                    />
                                </a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link mt-2 text-warning" href="#">Home</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link mt-2 text-dark" href="#">About us</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link mt-2 text-dark" href="#">Menu</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link mt-2 text-dark" href="#">Features</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link mt-2 text-dark" href="#">Contact us</a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link ml-5 text-dark" href="#">
                                    <button type='button' className={styles.btn}>Booking Now</button>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </header>
                <div className="row">
                    <div className={styles.colpon}>
                        <h2 className={styles.h}>Making time a good time <br/> by making food the good <br/> food.</h2>
                        <p className='mt-3'>There are many things are needed to start the Fast Food Business. You need <br/> not only Just Food Stalls with Persons but also specialized equipment</p>
                        <button type='button' className={styles.bttn}>Order Now</button>
                        <button type='button' className={styles.bttnn}>Order Now</button>
                    </div>
                    <div className={styles.img}>
                        <Image
                            src='/images/oshagap.png'
                            width={600}
                            height={550}
                        />
                    </div>
                    <div className="col-12 text-center">
                        <h3 className={styles.text}>Features</h3>
                        <h2><b>Food with a New Passion</b></h2>
                    </div>
                    <div className="col-4">
                        <div className={styles.pon}>
                            <div className={styles.siu}>
                                <Image
                                    src='/images/delivery.png'
                                    width={45}
                                    height={45}
                                />
                            </div>
                            <h3 className={styles.sui}>Food Delivery</h3>
                            <p className={styles.si}>It can be a very secure path to earn good money and make you very successful <br/> creative entrepreneur.</p>
                        </div>
                    </div>
                    <div className="col-4">
                        <div className={styles.pon}>
                            <div className={styles.siu}>
                                <Image
                                    src='/images/smile.png'
                                    width={45}
                                    height={45}
                                />
                            </div>
                            <h3 className={styles.sui}>Quality Food</h3>
                            <p className={styles.si}>It can be a very secure path to earn good money and make you very successful <br/> creative entrepreneur.</p>
                        </div>
                    </div>
                    <div className="col-4">
                        <div className={styles.pon}>
                            <div className={styles.siu}>
                                <Image
                                    src='/images/house.png'
                                    width={45}
                                    height={45}
                                />
                            </div>
                            <h3 className={styles.sui}>Super Taste</h3>
                            <p className={styles.si}>It can be a very secure path to earn good money and make you very successful <br/> creative entrepreneur.</p>
                        </div>
                    </div>
                </div>
            </div>

            <astets>
                <div className="container">
                    <div className="row">
                        <div className="col-6 mt-3">

                            <Image
                                src="/images/sui.png"
                                width={500}
                                height={450}
                                style={{borderRadius: 35}}

                            />
                        </div>
                        <div className="col-6 mt-3" style={{marginTop: 100}}>
                            <h5>About Us</h5>
                            <h4>Lorem ipsum dolor <br/>sit amet, consectetur adipisicing elit. <br/> Corporis dolorum
                                impedit placeat.</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur <br/>  adipisicing elit. Ad beatae dignissimos
                                doloremque error <br/> exercitationem expedita id ipsam iure laborum molestias <br/> nihil quam quas
                                quidem quis repudiandae sit suscipit vero, vitae?</p>
                            <div className={styles.ttt}>
                                <button type="button" className="mt-3 btn btn-warning" >Read More</button>
                            </div>
                        </div>
                    </div>
                </div>
            </astets>
            <main className={styles.main1}>

                <div className="container">
                    <div className="row">
                        <div className="col-12 text-center">
                            <h1 className={styles.txt1}>MENU</h1>
                            <h1 className={styles.txt2}> Full of treaty Love</h1>
                            <p className={styles.txt3}>There are many things are needed to start the Fast Food Business. You need not only Just Food Stalls<br/> with Persons but also specialized equipment, Skills to manage Customers, </p>
                        </div>

                    </div>
                </div>

            </main>
            <card>
                <div className="container">
                    <div className="row">
                        <div className="col-4">

                            <Image
                                src="/images/3.png"
                                width={300}
                                height={250}
                            />
                            <div className={styles.imgheader}>
                                <h4>Vegie Muffen </h4>
                                <h5>16$</h5>
                            </div>
                            <div className={styles.oshagap}>
                                <p className={styles.p1}>There are many things are needed to start<br/> the Fast Food Business.</p>

                            </div>
                            <div className={styles.main01}>
                                <button type="button" className={styles.btn01}>+</button>
                                <div className={styles.star}>
                                    <Image
                                        src="/images/star.png"
                                        width={75}
                                        height={12}/>
                                </div>
                            </div>
                        </div>
                        <div className="col-4">

                            <Image
                                src="/images/5.png"
                                width={300}
                                height={250}
                            />
                            <div className={styles.imgheader}>
                                <h4>Vegie Muffen </h4>
                                <h5>9$</h5>
                            </div>
                            <div className={styles.oshagap}>
                                <p className={styles.p1}>There are many things are needed to start<br/> the Fast Food Business.</p>

                            </div>
                            <div className={styles.main01}>
                                <button type="button" className={styles.btn01}>+</button>
                                <div className={styles.star}>
                                    <Image
                                        src="/images/star.png"
                                        width={75}
                                        height={12}/>
                                </div>
                            </div>
                        </div> <div className="col-4">

                        <Image
                            src="/images/1.png"
                            width={300}
                            height={250}
                        />
                        <div className={styles.imgheader}>
                            <h4>Vegie Muffen </h4>
                            <h5>22$</h5>
                        </div>
                        <div className={styles.oshagap}>
                            <p className={styles.p1}>There are many things are needed to start<br/> the Fast Food Business.</p>

                        </div>
                        <div className={styles.main01}>
                            <button type="button" className={styles.btn01}>+</button>
                            <div className={styles.star}>
                                <Image
                                    src="/images/star.png"
                                    width={75}
                                    height={12}/>
                            </div>
                        </div>

                    </div> <div className="col-4 mt-5">

                        <Image
                            src="/images/2.png"
                            width={300}
                            height={250}
                        />
                        <div className={styles.imgheader}>
                            <h4>Vegie Muffen </h4>
                            <h5>51$</h5>
                        </div>
                        <div className={styles.oshagap}>
                            <p className={styles.p1}>There are many things are needed to start<br/> the Fast Food Business.</p>

                        </div>
                        <div className={styles.main01}>
                            <button type="button" className={styles.btn01}>+</button>
                            <div className={styles.star}>
                                <Image
                                    src="/images/star.png"
                                    width={75}
                                    height={12}/>
                            </div>
                        </div>
                    </div> <div className="col-4 mt-5">
                        <Image
                            src="/images/3.png"
                            width={300}
                            height={250}
                        />
                        <div className={styles.imgheader}>
                            <h4>Vegie Muffen </h4>
                            <h5>23$</h5>
                        </div>
                        <div className={styles.oshagap}>
                            <p className={styles.p1}>There are many things are needed to start<br/> the Fast Food Business.</p>

                        </div>
                        <div className={styles.main01}>
                            <button type="button" className={styles.btn01}>+</button>
                            <div className={styles.star}>
                                <Image
                                    src="/images/star.png"
                                    width={75}
                                    height={12}/>
                            </div>
                        </div>
                    </div>
                        <div className="col-4 mt-5">

                            <Image
                                src="/images/4.png"
                                width={300}
                                height={250}
                            />
                            <div className={styles.imgheader}>
                                <h4>Vegie Muffen </h4>
                                <h5>16$</h5>
                            </div>
                            <div className={styles.oshagap}>
                                <p className={styles.p1}>There are many things are needed to start<br/> the Fast Food Business.</p>

                            </div>
                            <div className={styles.main01}>
                                <button type="button" className={styles.btn01}>+</button>
                                <div className={styles.star}>
                                    <Image
                                        src="/images/star.png"
                                        width={75}
                                        height={12}/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </card>

            <app>
             <Image
             src="/images/App.png"
             width={1500}
             height={700}/>
            </app>
            <testimonial>
                <div className="container">
                    <div className="row">
                        <div className="col-12 text-center">
                            <p className={styles.test}> TESTIMONIAL</p>
                            <div className={styles.test1}>Making Food great again and again</div>
                            <div className={styles.test2}>You need not only Just Food Stalls with Persons but also specialized equipment, Skills to manage<br/> Customers, Effective Product catlogues etc to make your.</div>
                        </div>
                    </div>
                </div>
            </testimonial>

            <opacha>
                <div className="container">
                    <div className="row">
                        <div className="col-12 text-center">
                            <div className={styles.immg}>
                                <Image
                                    src="/images/opacha.png"
                                    width={70}
                                    height={70}
                                    />
                            </div>
                            <div className={styles.need}>You need not only Just Food Stalls with Persons but also specialized<br/>
                            equipment, Skills to manage Customers, Effective Product catlogues<br/> etc very successful to make your.</div>
                            <div className={styles.immp}>
                                <Image
                                    src="/images/star.png"
                                    width={100}
                                    height={20} />
                            </div>

                            <div className={styles.test11}>Augusta W. Reynoso</div>
                            <div className={styles.test2}>UI&UX DeSIGNER</div>

                        </div>
                    </div>
                </div>
            </opacha>
<div className={styles.footer1}>
            <div className="de-footer text-center mt-5" style={{height: 300, backgroundColor: "#FBF1E7"}}>
                <h4 style={{color: "#DC780B", paddingTop: 30}}>CONTACT</h4>

                <h3 className="mt-3">Food Stalls with Persons but also specialized <br/> equipment, Skills to manage.</h3>
                <div className="form  d-flex justify-content-center align-items-center m-auto" style={{width: 600, paddingTop: 30}}>
                    <input
                        type="text"
                        className="form-control"
                        placeholder="Enter your message"
                        style={{height: 50}}
                    />
                    <button type="button" className="btn" style={{backgroundColor: "#DC780B", color: "white", height: 50}}>Send</button>
                </div>
            </div>
            <div className="footer">
                <Image
                    src='/images/Footer.png'
                    width={1536}
                    height={420}
                />
            </div>
        </div>
<div className={styles.con}>
            <div className="container-fluid bg-dark">
                <div className="row">
                    <div className="col-12 d-flex">
                        <div className={styles.foot}>
                            <Image
                            src="/images/logo.png"
                            width={100}
                            height={100}/>
                            <p>www.company name.com</p>
                            <p>www.company name.com</p>
                            <p>Phone: +7 485-118-03-25</p>

                        </div>
                        <div className={styles.foot}>
<h4>Company</h4>
                            <p>Landingpage</p>
                            <p>Documentation</p>
                            <p>Referral Program</p>
                            <p>UI & UX Design</p>
                            <p>Web Design</p>

                        </div>
                        <div className={styles.foot}>
<h4>Menu</h4>
                            <p>Landingpage</p>
                            <p>Documentation</p>
                            <p>Referral Program</p>
                            <p>UI & UX Design</p>
                            <p>Web Design</p>

                        </div>
                        <div className={styles.foot}>
<h4>Home</h4>
                            <p>Landingpage</p>
                            <p>Documentation</p>
                            <p>Referral Program</p>
                            <p>UI & UX Design</p>
                            <p>Web Design</p>

                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>



    )
}